name = "SolarIrradiance"
uuid = "2d82c817-3d9d-4cdc-a094-95b0b9950c3c"
authors = [
    "Pierre Galloo-Beauvais <pierre.galloo-beauvais@ens-rennes.fr>",
    "Pierre Haessig <pierre.haessig@centralesupelec.fr>"
]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
